### ISSUE TITLE
a little help with auth setup?

### ISSUE THREAD

**Issue by fsiler** [thingol/gdriveshell#1]
I get the following- maybe a little prompting about what to do, format of the dotfile, etc?  Thanks.

    Traceback (most recent call last):
      File "/Users/fms/Library/Python/3.6/bin/gdriveshell", line 588, in <module>
        GDriveShell().cmdloop()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 105, in cmdloop
        self.preloop()
      File "/Users/fms/Library/Python/3.6/bin/gdriveshell", line 372, in preloop
        load_config()
      File "/Users/fms/Library/Python/3.6/bin/gdriveshell", line 60, in load_config
        __CLIENT_ID__ = cfg['auth']['client_id']
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 959, in __getitem__
        raise KeyError(key)
    KeyError: 'auth'

**Comment by thingol** [comment]
It makes me wonder why I didn't include a sample file in the repo. This oversight shall be remedied by the end of the day!

**Comment by thingol** [comment]
Turns I had a sample in README.md, but it was mangled by Markdown parser. Anyways, the config file ist in the MS .ini format.

Issue resolved?

**Comment by thingol** [comment]
Silence is golden ;)
